### ISSUE TITLE
GUI EUA Checklist

### ISSUE THREAD

**Issue by sneakers-the-rat** [CohenLabPrinceton/Ventilator-Dev#100]
Jonny collecting todo items that are necessary for the EUA

- [ ] https://github.com/CohenLabPrinceton/Ventilator-Dev/issues/98 - constraints on controlled values
- [ ] https://github.com/CohenLabPrinceton/Ventilator-Dev/issues/88 - Switching displayed units
- [ ] https://github.com/CohenLabPrinceton/Ventilator-Dev/issues/87 - Display error tolerance
- [ ] https://github.com/CohenLabPrinceton/Ventilator-Dev/issues/97 - Display if alternative power supply in use & how long has been on battery power.
